
services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: postgres-ecommerce
    environment:
      POSTGRES_DB: commerce_db
      # You should definitely change the password in production
      POSTGRES_PASSWORD: enki
      POSTGRES_USER: enki
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      
  ###< doctrine/doctrine-bundle ###
  pgadmin:
    container_name: pgadmin4-ecommerce
    image: dpage/pgadmin4
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: enki@enki.com
      PGADMIN_DEFAULT_PASSWORD: enki
    ports:
      - "5050:80"
      
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-ecommerce
    ports: [5672, 15672]



volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ####
